version: '3.8'

services:
  postgres:
    container_name: swiggy-backend-nestjs
    image: postgres
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - '5434:5432'
    restart: unless-stopped